version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "aws-connect-vanity"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1xe63lgivr3bp"
s3_prefix = "aws-connect-vanity"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
