AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  lambda-python3.9

  Sample SAM Template for lambda-python3.9 AWS Connect Vanity Number

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 30

Resources:
  LambdaFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: vanitynumber/
      Handler: app.lambda_handler
      Runtime: python3.9
      Role: arn:aws:iam::766162985452:role/myLambdaRole
      Policies: AmazonDynamoDBFullAccess

  ConnectPerm:
    Type: AWS::Lambda::Permission
    DependsOn: LambdaFunction
    Properties:
      Action: lambda:invokeFunction
      FunctionName: !GetAtt LambdaFunction.Arn
      Principal: connect.amazonaws.com
      SourceAccount: !Ref AWS::AccountId

  DynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
      - AttributeName: phoneNum
        AttributeType: String
      KeySchema:
        - AttributeName: phoneNum
          KeyType: HASH
      TableName: customer_Vanity_Numbers

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  # LambdaFunction:
  #   Description: "Lambda Function for Connect Vanity Numbers"
  #   Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  LambdaFunction:
    Description: "Lambda Function for Connect Vanity Numbers ARN"
    Value: !GetAtt LambdaFunction.Arn
  LambdaFunctionIamRole:
    Description: "Implicit IAM Role created for Vanity Number function"
    Value: !GetAtt LambdaFunctionRole.Arn
